services:
  - us.gcr.io/planet-gcr/terraflop/planet-docker:dind

variables:
  DOCKER_HOST: localhost:2375
  DOCKER_DRIVER: overlay2
  CGO_ENABLED: "0"

stages:
  - test
  - build-and-push

test:
  stage: test
  image: golang:1.11-alpine3.8
  tags:
    - gcp-terraflop
  before_script:
    - apk update && apk add git curl
    - curl -sSL -o /bin/dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x /bin/dep
    - curl -sSL -o /gml.tgz https://github.com/alecthomas/gometalinter/releases/download/v2.0.12/gometalinter-2.0.12-linux-amd64.tar.gz && tar zxvf /gml.tgz -C /bin --strip-components=1
    - mkdir -p /go/src/github.com/planetlabs
    - ln -s /code/product/legion /go/src/github.com/planetlabs/legion && cd /go/src/github.com/planetlabs/legion
    - dep ensure
  script:
    - gometalinter
    - go test -v -cover ./...

build-and-push:
  stage: build-and-push
  image: docker:latest
  tags:
    - gcp-terraflop
  only:
    - master
  script:
    - docker build --tag us.gcr.io/planet-gcr/legion:${CI_COMMIT_SHA:0:8} .
    - docker push us.gcr.io/planet-gcr/legion:${CI_COMMIT_SHA:0:8}
