services:
  - us.gcr.io/planet-gcr/terraflop/planet-docker:dind

variables:
  DOCKER_HOST: localhost:2375
  DOCKER_DRIVER: overlay2
  CGO_ENABLED: "0"

stages:
  - test
  - build-and-push

test:
  stage: test
  image: golang:1.11-alpine3.8
  tags:
    - gcp-terraflop
  before_script:
    - apk update && apk add git curl
    - curl -sSL -o /dep https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64 && chmod +x /dep
    - ln -s /code /go/src/code.earth.planet.com && cd /go/src/code.earth.planet.com/product/legion
    - /dep ensure
  script:
    - go run github.com/alecthomas/gometalinter
    - go test -v -cover ./...

build-and-push:
  stage: build-and-push
  image: docker:latest
  tags:
    - gcp-terraflop
  only:
    - master
  script:
    - docker build --tag us.gcr.io/planet-gcr/legion:${CI_COMMIT_SHA:0:8} .
    - docker push us.gcr.io/planet-gcr/legion:${CI_COMMIT_SHA:0:8}
